export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CATEGORIES: "SET_CATEGORIES", // Ensure this is defined
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY", // Ensure this is defined
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
